import Head from 'next/head'
import Script from 'next/script'
import styles from '../../styles/Home.module.css'
// import Link from 'next/link'
// import styles from '../../styles/post.module.css'


// import './styles/global.css'

const Post1 = () => {

       
  return (
    <div  className={styles.container}>

<Head>
{/* 
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" /> */}
< >
      <meta charSet="UTF-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=, initial-scale=1.0" />
      <title>Young Professionals</title>
      {/* Font Awesome */}
      <link
        rel="stylesheet"
        href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      />
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
      />
      {/* <link rel="stylesheet" href="normalize.css"> */}
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
        crossOrigin="anonymous"
      />
      <link rel="stylesheet" href="styles.css" />
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css"
        rel="stylesheet"
      />
      {/* Google fonts */}
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
      />
    </>

</Head>
<main className={styles.main}>

{/* <main className={styles.main}> */}

{/* Navbar */}

        <nav
            className="navbar navbar-expand-lg navbar-light bg-warning fixed-top px-5 py-2 shadow-5-strong"
            style={{ zIndex: 5 }}
        >
            <div className="container-fluid">
            <a className="navbar-brand" href="#">
        <img
            src="assets/yps-logo.png"
            style={{ height: 50, width: 70, marginTop: 0 }}
            alt="logo"
        />
        </a>
        <button
                className="navbar-toggler"
                type="button"
                data-mdb-toggle="collapse"
                data-mdb-target="#navbarExample01"
                aria-controls="navbarExample01"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
        <i className="fas fa-bars" />
        <span />
        <span />
        <span />
        </button>
        {/* <div class="collapse navbar-collapse justify-content-between" id="navbarExample01"> */}
        <div
        className="collapse navbar-collapse justify-content-between ml-auto"
        id="navbarExample01"
        >
        <ul
        className="navbar-nav ms-auto mb-2 mb-lg-0"
        style={{ fontSize: 20, fontFamily: 'rooneysans', fontWeight: "bold" }}
        >
        <li  className="nav-item active">
            <a className="nav-link" aria-current="page" href="../#" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }} >
            Home
            </a>
        </li>
        <li className="nav-item">
            <a className="nav-link" href="../#vision" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>
            Vision
            </a>
        </li>
        <li className="nav-item">
            <a className="nav-link" href="../#gallery" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>
            Gallery
            </a>
        </li>
        <li className="nav-item">
            <a className="nav-link" href="../#blog" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>
            Blog
            </a>
        </li>
        <li className="nav-item">
            <a className="nav-link" href="#footer" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>
            Contact
            </a>
        </li>
        </ul>
        </div>
        </div>
        </nav>

<div className="container mt-5 ">
  <div className="row ">
    <div className="col-lg-8">
      {/* Post content*/}
      <article>
        {/* Post header*/}
        <header className="mt-4 ">
          {/* Post title*/}
          <h1 className="fw-bolder mt-10" style={{ fontFamily: 'rooneysans'}}>WHY IS GOD SILENT?</h1>
        
        </header>
        {/* Preview image figure*/}
        <figure className="mb-4">
          <img
            className="img-fluid rounded"
            src="assets/BlogPost.jpeg"
            alt="..."
          />
        </figure>
        {/* Post content*/}
        <section className="mb-5">
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans'}}>
          And though the LORD gives you the bread of adversity and the water of affliction, yet your teachers shall not be removed into a corner any more, but your eyes shall see your teachers.
– Isiah 30:20 KJV
The teacher is always silent during a test.
A good teacher anyways, not the miracle center kind, the one who came to class every day, prepped his students, even did weekend classes and online videos during the COVID-19 pandemic.


          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
          The one who took time to explain, to bring specimens from out of school just so you could experience the concept in real life.
          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
          As I paint this picture, maybe an Agric teacher comes to mind, a biology teacher? Your fine arts teacher? Or maybe your Math teacher, but you’re too scared to admit it.Oh well, we’ve all at some point had a really good teacher and we knew before exams that we were not getting any assistance. We also knew it was not from a place of wickedness but from a place of confidence that the teacher has done all that was needed and taught us well enough to trust in our ability to take the exams without cheating, or fear of failure.
          </p>
          <h3 className="fw-bolder mb-4 mt-5" style={{ fontFamily: 'rooneysans' }}>
          What is the purpose of a test?
          </h3>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
          School sweet but na exam spoil am. Why do Christians go through tests? What do distress, challenges, and tribulation do for our journey and worse off, why does our teacher seem to be silent through it? Sometimes it takes us unawares, like a “tear a piece of paper and write your name” kind of flash test on a Monday morning.

          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
          A spiritual gbas gbos, unexpected, seemingly undeserved. But like school, to move on to the next level, we’ve got to show that we’ve understood all the current level has taught us, as the knowledge gained is not for the school or the teacher, but for our own good. For if we graduate from a class without gaining the prerequisite knowledge, we are bound to struggle in the next class.

          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
          Did you ever struggle with a subject? You’re in class, everyone is using a compass and meter rule but you just for the love of God, cannot understand what’s going on. In situations like this, there’s a high probability that you missed class on the first day the elementary was taught, or you were present but did not understand it at all, and except by divine intervention or through revision, you’re most likely to hate that topic for the rest of your life and probably fail it as well. Life is kind of like that, but God doesn’t want us to hate any part of life.

          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
          We’re supposed to enjoy living. “Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation. Selah.”– Psalm 68:19

          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
            You need to be equipped for the next level and you can only do that… successfully if you’ve passed the previous stage, understood the concept, and grabbed the fundamentals enough for the subsequent layers to come. “If the foundations be destroyed, what can the righteous do?” -Psalm 11:3
            So, consider the waiting, the delay, the disappointment as a building phase.
            Remember what you do ultimately determines the quality of your promotion to the next stage.

          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
          “For the LORD God is a sun and shield: the LORD will give grace and glory: no good thing will he withhold from them that walk uprightly.”– Psalm 84:11
“ But God’s not finished. He’s waiting around to be gracious to you.
    He’s gathering strength to show mercy to you.
God takes the time to do everything right—everything.
    Those who wait around for him are the lucky ones. “–Isaiah 30:18


          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>
             So yeah, the teacher may be silent but  He’s not absent, He’s watching over you to come out strong and if you’re reading this today, it serves as a reminder that the Teacher may not be silent after all
          </p>
          <p className="fs-5 mb-4" style={{ fontFamily: 'rooneysans' }}>

          I leave you with this verse:
“ …the Master won’t ever walk out and fail to return.If he works severely, he also works tenderly. His stockpiles of loyal love are immense.He takes no pleasure in making life hard,in throwing roadblocks in the way:Lamentations 3:31-33

          </p>
        </section>
      </article>
    </div>
    {/* Side widgets*/}
    <div className="col-lg-4 mt-5">
     
      {/* Side widget*/}
      <div className="card mb-4">
        <div className="card-header" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>About YPS</div>
        <div className="card-body" style={{ fontFamily: 'rooneysans'}}>
          {" "}
          A group of young professionals in from different works of life across
          the globe who love God and are passionate about missions.
        </div>
      </div>
      <div className="card mb-4">
        <div className="card-header"style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>About YPS</div>
        <div className="card-body" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>
          {" "}
          Give to the work we do here: Name- YPs in Missions, Acc No-
          9981034817, Bank- PROVIDUS BANK
        </div>
      </div>
    </div>
  </div>


  {/* Testimonials */}
  <section id="testimonials" className="mt-5 ">
    <h1
      className="text-center mb-5 fs-900 mb-2"
      style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}
    >
      Missions Trip Testimonials
    </h1>
    {/* Carousel wrapper */}
    <div
      id="carouselMultiItemExample"
      className="carousel slide carousel-dark text-center"
      data-mdb-ride="carousel"
    >
      {/* Controls */}
      <div className="d-flex justify-content-center mb-4"></div>
      {/* Inner */}
      <div className="carousel-inner py-4">
        {/* Single item */}
        <div className="carousel-item active">
          <div className="container">
            <div className="row">
              <div className="col-lg-4">
                <img
                  className="rounded-circle shadow-1-strong mb-4"
                  src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp"
                  alt="avatar"
                  style={{ width: 150 }}
                />
                <h5 className="mb-3" style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}>Anna Deynah</h5>
                <p >UX Designer</p>
                <p className="text-muted"  style={{ fontFamily: 'rooneysans'}}>
                  <i className="fas fa-quote-left pe-2"/>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod
                  eos id officiis hic tenetur quae quaerat ad velit ab hic
                  tenetur.
                </p>
              </div>
              <div className="col-lg-4 d-none d-lg-block">
                <img
                  className="rounded-circle shadow-1-strong mb-4"
                  src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(32).webp"
                  alt="avatar"
                  style={{ width: 150 }}
                />
                <h5 className="mb-3">John Doe</h5>
                <p>Web Developer</p>
                <p className="text-muted "  style={{ fontFamily: 'rooneysans'}}>
                  <i className="fas fa-quote-left pe-2"/>
                  Ut enim ad minima veniam, quis nostrum exercitationem ullam
                  corporis suscipit laboriosam, nisi ut aliquid commodi.
                </p>
              </div>
              <div className="col-lg-4 d-none d-lg-block">
                <img
                  className="rounded-circle shadow-1-strong mb-4"
                  src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(10).webp"
                  alt="avatar"
                  style={{ width: 150 }}
                />
                <h5 className="mb-3">Maria Kate</h5>
                <p>Photographer</p>
                <p className="text-muted" style={{ fontFamily: 'rooneysans'}}>
                  <i className="fas fa-quote-left pe-2" />
                  At vero eos et accusamus et iusto odio dignissimos ducimus qui
                  blanditiis praesentium voluptatum deleniti atque corrupti.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></Script>
        {/* <Script src="script.js"></Script> */}

        <Script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"
        ></Script>   
    
  </section>

  
  {/* Footer */}
</div>

<>
  <footer
    id="footer"
    className="page-footer font-small blue pt-4 mt-10"
    style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}
  >
    <div className="container-fluid text-center text-md-left ">
      {/* Grid row */}
      <div className="row">
        {/* Grid column */}
        <div className="col-md-6 mt-md-0 mt-3">
          {/* Content */}
          <h5
            className="text-uppercase"
            style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}

          >
            About YPS
          </h5>
          <p>
              A group of young professionals in from different works of life across the globe who love
             God and are passionate about missions.
          </p>
        </div>
        {/* Grid column */}
        <hr className="clearfix w-100 d-md-none pb-3" />
        {/* Grid column */}
        <div className="col-md-3 mb-md-0 mb-3">
          <h5
            className="text-uppercase"
            style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}
          >
            Follow us on
          </h5>
          <div className="icon">
            <ul className="list-unstyled d-flex justify-content-center text-warning mb-0">
              {/* <li>
                <a
                  className="fab fa-twitter px-2 font-weight-bold"
                  href="https://getbootstrap.com/docs/4.0/components/card/"
                />
              </li> */}
              <li>
                <a
                  className="fab fa-instagram px-2 font-weight-bold"
                  href="https://instagram.com/ypsinmissions?igshid=YmMyMTA2M2Y="
                />
              </li>
              <li>
                <a
                  className="fab fa-facebook px-2 font-weight-bold"
                  href="https://getbootstrap.com/docs/4.0/components/card/"
                />
              </li>
              <li>
                <a
                  className="fab fa-youtube px-2 font-weight-bold"
                  href="https://www.youtube.com/watch?v=2T27M-8Aeh4&t=210s"
                />
              </li>
            </ul>
          </div>
        </div>
        <div className="col-md-3 mb-md-0 mb-3">
          <h5
            className="text-uppercase"
            style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}
          >
            Join Us Here
          </h5>
          <div className="icon">
            <a
              className="btn-outline-warning btn-lg"
              style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}
              href="https://forms.gle/McZJpbFZ2p8WsW6K9"
              role="button"
            >
              {" "}
              JOIN{" "}
            </a>
          </div>
        </div>
      </div>
    </div>
    {/* Footer Links */}
    {/* Copyright */}
    <div className="footer-copyright text-center py-3" style={{ fontFamily: 'rooneysans', fontWeight: "bold", fontSize: 15 }}>
      © 2022 Copyright:
      <span style={{ fontFamily: 'rooneysans', fontWeight: "bold" }}> Young Professionals</span>
    </div>
    {/* Copyright */}
  </footer>

</>
</main>
</div>
)
}
export default Post1;
